Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Local public key content
  LOCAL_PUBLIC_KEY = <<-KEY
  your ssh rsa public key here
  KEY

  # ---------------- Server 1 ----------------
  config.vm.define "server1" do |server|
    server.vm.hostname = "server1"
    server.vm.network "private_network", ip: "192.168.56.11"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      mkdir -p /home/vagrant/.ssh
      echo '#{LOCAL_PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # ---------------- Server 2 ----------------
  config.vm.define "server2" do |server|
    server.vm.hostname = "server2"
    server.vm.network "private_network", ip: "192.168.56.12"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    server.vm.provision "shell", inline: <<-SHELL
      mkdir -p /home/vagrant/.ssh
      echo '#{LOCAL_PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # ---------------- Server 3 ----------------
  config.vm.define "server3" do |server|
    server.vm.hostname = "server3"
    server.vm.network "private_network", ip: "192.168.56.13"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      mkdir -p /home/vagrant/.ssh
      echo '#{LOCAL_PUBLIC_KEY}' >> /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end

